name: new_idf
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        hw_version: [hw1, hw2]
        br_config:
          [3do, cdi, dreamcast, gamecube, gbahd, genesis, jaguar, jvs_arcade, n64, nes,
          parallel_1p, parallel_1p_3v3, parallel_2p, parallel_2p_3v3, pc_engine, pcfx,
          playstation, saturn, snes, universal, virtualboy, wii_extension, ogx360]
        include:
          - hw_version: dbg
            br_config: pad_test
          - hw_version: dbg
            br_config: qemu
          - hw_version: dbg
            br_config: qemu_bt_trace_replay
          - hw_version: dbg
            br_config: qemu_bt_trace_replay_test
    runs-on: ubuntu-latest

    steps:
    - name: Clean working directory
      run: |
        find . -name . -o -prune -exec rm -rf -- {} +
    - name: Install ESP-IDF prerequisite
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util
    - name: Set python3 default
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && alias pip=pip3
    - name: Clone BlueRetroRoot
      run: git clone https://github.com/darthcloud/BlueRetroRoot.git .
    - name: Fetch submodules
      run: |
        git submodule update --init --remote
        cd esp-idf
        git submodule update --init --recursive
        cd ../BlueRetro
        git submodule update --init --recursive
    - name: Checkout main repo
      working-directory: ./BlueRetro
      run: |
        git fetch --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git "+refs/heads/*:refs/remotes/origin/*"
        git fetch --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git "+refs/pull/*:refs/remotes/origin/pr/*"
        git checkout ${{ github.sha }} || git checkout ${{ github.event.pull_request.head.sha }}
        git submodule update --init --recursive
    - name: Install ESP-IDF
      working-directory: ./esp-idf
      run: sh ./install.sh
      env:
        IDF_TOOLS_PATH : "${{ github.workspace }}/BlueRetroRoot/"
    - name: Build with ESP-IDF
      working-directory: ./BlueRetro
      run: |
        . ../esp-idf/export.sh
        echo "br_version=$(git describe --always --tags --dirty)" >> $GITHUB_ENV
        rm -fr build
        echo "$(git describe --always --tags --dirty) ${{ matrix.hw_version }} ${{ matrix.br_config }}" | cut -c -31 > version.txt
        cat version.txt
        cp configs/${{ matrix.hw_version }}/${{ matrix.br_config }} sdkconfig
        BR_HW=_${{ matrix.hw_version }} BR_SYS=_${{ matrix.br_config }} idf.py reconfigure build
      env:
        IDF_TOOLS_PATH : "${{ github.workspace }}/BlueRetroRoot/"
    - name: Copy OTA initial binary
      working-directory: ./BlueRetro/build
      run: |
        mkdir ota
        mv ota_data_initial.bin ota/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.br_version }}_${{ matrix.hw_version }}
        path: |
          BlueRetro/build/partition_table/partition-table.bin
          BlueRetro/build/bootloader/bootloader.bin
          BlueRetro/build/ota/ota_data_initial.bin
          BlueRetro/build/BlueRetro*.bin
        if-no-files-found: error
